# Auto-generated by USB WebSerial UI. You can still edit manually.
# [MIDI CH, MIDI CMD, source port, destination port]
# -1 means ANY. Ports are 0..5.

MIDIRT = [
    # Вход 1 на корпусе, в коде 0
    [-1, -1, 0, 0],

    # Вход 2 на корпусе, в коде 1
    [-1, -1, 1, 1],

    # Вход 3 на корпусе, в коде 2
    [-1, -1, 2, 2],

    # Вход 4 на корпусе, в коде 3
    [-1, -1, 3, 3],

    # Вход 5 на корпусе, в коде 4
    [-1, -1, 4, 4],

    # Вход 6 на корпусе, в коде 5
    [-1, -1, 5, 5],

]

MIDIDEF = -1
